### ISSUE TITLE
Undefined method getNamespace

### ISSUE THREAD

**Issue by mstaack** [michaelbonds/lumen-make#1]
i am getting: PHP Fatal error:  Call to undefined method App\Application::getNamespace() 
lumen 5.2.3

any hints?

**Comment by mstaack** [comment]
i just tried it with a fresh lumen install

```
➜  lumen-make-demo  ./artisan make:controller DemoController
PHP Fatal error:  Call to undefined method Laravel\Lumen\Application::getNamespace() in /home/max/lumen-make-demo/vendor/illuminate/console/GeneratorCommand.php on line 103


  [Symfony\Component\Debug\Exception\FatalErrorException]             
  Call to undefined method Laravel\Lumen\Application::getNamespace()  
```

how is the namespace stuff to be implemented? should i create this method in the application class?
then we should update the docs..

btw:  thanks for this package! i really think it speeds up development time :)

**Comment by mstaack** [comment]
adding this works but i think its not really beautiful:

```
    public $namespace = 'App';

    /**
     * Get the application namespace.
     *
     * @return string
     *
     * @throws \RuntimeException
     */
    public function getNamespace()
    {
        if (!is_null($this->namespace)) {
            return $this->namespace;
        }
        throw new \Exception('Unable to detect application namespace.');
    }
```

**Comment by webrgp** [comment]
Where did you add that?

**Comment by michaelbonds** [comment]
Holy crap, guys. I am so sorry.
I just saw where you guys commented on here. I haven't been able to work on this package in a while, or even use it. 
I just installed it on a fresh lumen install, and alas, I got the error as well. 
I'll update later with a fix.

Again, I am so sorry!

**Comment by michaelbonds** [comment]
Hey guys,
Just in case you are all still having this problem, just update your dependency to 'dev-develop' and it should work fine. I'll put a subversion up on packagist and update the docs. I don't have the time at the moment, but I will handle it this weekend and update here.
Let me know if you guys have anymore issues/questions.
